name: Deploy to VPS
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 19.1
        uses: actions/setup-node@v2
        with:
          node-version: 19.1.0

      - name: Install dependencies
        run: npm ci

      - name: Linter
        run: npm run lint --max-errors=0 --max-warnings=3
        if: ${{failure}}

      - name: Build app
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: dist/*
          target: /var/www/vps-zap468762-3.zap-srv.com
