name: Execute command on server
on:
  push:
    branches:
      - main
jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server and run command
        env:
          SSH_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          echo "$SSH_PASSWORD" | sshpass -p - ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} 'bash -c "cd /var/www/vps-zap468762-3.zap-srv.com && git pull"'
